# Generated by Django 4.1.3 on 2022-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad_bebible', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Milanesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_relleno', models.CharField(max_length=100)),
                ('coccion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('acompañamiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gusto', models.CharField(max_length=100)),
                ('porciones', models.IntegerField()),
                ('estilo', models.CharField(max_length=100)),
            ],
        ),
    ]
